### ISSUE TITLE
Feature request: Integrate to automatically populate values

### ISSUE THREAD

**Issue by jschlies** [MobileTribe/commit-template-idea-plugin#1]
Feature request:
Integrate to automatically populate:
- Current Branch
- Date/Time
- Add functionality to insure that every commit message is unique

**Comment by darrachequesne** [comment]
Hi!

What is the format expected for the branch / date? (it's not part of the "classic" template [here](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format))

Regarding the message, that may indeed be interesting (along with the ability to reuse existing scopes), but it involves being able to parse the result of the `git log` command, which is a bit more complex than what is done today.

Note: the sources of that [plugin](https://plugins.jetbrains.com/plugin/3033-git-integration) may be useful.

**Comment by jschlies** [comment]
I was thinking about this as a default commit message : 
```
<type>(<scope>): <subject> Commit to {BRANCH_NAME} at {DATE_IN_READABLE_FORMAT}
<BLANK LINE>
<body>
<BLANK LINE>
<footer>

```
I would also request that {DATE_IN_READABLE_FORMAT} includes seconds to ensure (mostly) a unique commit message.  {DATE_IN_READABLE_FORMAT} should be in a sortable format (YYYY-MM:DD:SS for example.

**Comment by jschlies** [comment]
Does this have a status???

**Comment by sebthauvette** [comment]
The branch and datetime is already present in the commit logs. Why do you need to also add it to the comment ? I think most people would not want this as it's redundant. 

Maybe there could be a default subject that's configurable with variables like branch and date. This way you could configure yours like you want but others could leave it empty and keep the current behavior.

**Comment by darrachequesne** [comment]
As said before, we'd like to keep the format used by the Angular team: https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits

The template could become configurable with user-defined fields, but I'm afraid it's out of the scope of this plugin (at least for now). Closing now, please reopen if needed.
