### ISSUE TITLE
Type of change: use radio buttons instead of dropdown list

### ISSUE THREAD

**Issue by stokito** [MobileTribe/commit-template-idea-plugin#12]
It's will be much faster to select type of change by clicking or radio button instead of dropdown list.
There is not so much options so we can put them all to dialog

**Comment by gaelgubian** [comment]
Number of options is not fixed, it depends of your project size. Don't do this for everyone ! Maybe only if there is 5 or less options.

**Comment by darrachequesne** [comment]
Closed by https://github.com/MobileTribe/commit-template-idea-plugin/commit/03eb51250f7b773767f1068889ca99856684338d

The window is a bit bigger now:

![image](https://user-images.githubusercontent.com/13031701/97936802-fe07b400-1d7c-11eb-843d-e9f8762117a1.png)
