### ISSUE TITLE
add support for the new commit panel

### ISSUE THREAD

**Issue by eman1986** [MobileTribe/commit-template-idea-plugin#19]
Jetbrains recently added a new commit panel so you don't need to open up a dialog, but this plugin doesn't seem to support that. It'd be really nice if it did.

**Comment by darrachequesne** [comment]
The button should already appear in the new commit panel:

![image](https://user-images.githubusercontent.com/13031701/97791973-813bd500-1bd8-11eb-8460-3debacc6b652.png)

Intellij IDEA 2020.2 (build 202.7660.26)

Doesn't it work for you?

**Comment by eman1986** [comment]
Looks to be fine now
