### ISSUE TITLE
Support sign-off commit

### ISSUE THREAD

**Issue by teobais** [MobileTribe/commit-template-idea-plugin#20]
Hi,

I am actually not using this plugin, but wouldn't it be nice if we could also support a sign-off footer option?

Thodoris

**Comment by darrachequesne** [comment]
You should already be able to sign-off your commit: 

![image](https://user-images.githubusercontent.com/13031701/97791991-cbbd5180-1bd8-11eb-8ef2-e27188f7bc53.png)
