### ISSUE TITLE
I upgraded the plug-in to facilitate the management of scope files, added Idea Toolwindow, and managed scope through tree diagram.

### ISSUE THREAD

**Issue by VcStrong** [MobileTribe/commit-template-idea-plugin#21]
I upgraded the plug-in to facilitate the management of scope files, added Idea Toolwindow, and managed scope through tree diagram. Thanks!

Plugin New Version:https://github.com/VcStrong/JetpackMVVM/tree/master/gct

**Comment by darrachequesne** [comment]
Could you please open a pull request with your changes? Thanks!
