### ISSUE TITLE
The recommended scope is empty

### ISSUE THREAD

**Issue by edte** [MobileTribe/commit-template-idea-plugin#26]
## IDE
GoLand 2020.2.3

## version
1.2.0

## question

when i click the <-
![image](https://user-images.githubusercontent.com/50194671/113478518-cf247400-94bb-11eb-9dd1-7664f0f85513.png)

there is empty where should not be empty,That means I have to type the scope manually,is it a feature,or a bug?
![image](https://user-images.githubusercontent.com/50194671/113478477-91bfe680-94bb-11eb-86bf-c400c15fa06e.png)

**Comment by darrachequesne** [comment]
The scope is user-defined, and can be empty.

Reference: https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#scope

Example: https://github.com/angular/angular.js/commit/a90d0cbbba7a88f0ddacf95136a72abeb932363f

The existing scopes should be parsed from the git history. Isn't that the case?
