### ISSUE TITLE
Bug BREAKING CHANGE and Closes

### ISSUE THREAD

**Issue by dinoyee** [MobileTribe/commit-template-idea-plugin#8]
![image](https://user-images.githubusercontent.com/8397043/48246967-70628980-e42c-11e8-8fd6-9903c3933568.png)
![image](https://user-images.githubusercontent.com/8397043/48246976-7eb0a580-e42c-11e8-9b23-8225321c11a4.png)

**Comment by starchou** [comment]
the same issue for me

**Comment by darrachequesne** [comment]
Hi, it seems both fields were mixed up, I'll publish a fix asap.
